require("lze").load({
	{ import = "partials.plugins.colorscheme" },
	{
		"bullets.vim",
		for_cat = "notes",
		ft = "markdown",
	},

	{ import = "partials.plugins.opencode" },
	{ import = "partials.plugins.completion" },
	{ import = "partials.plugins.conform" },
	{ import = "partials.plugins.direnv" },
	{ import = "partials.plugins.flash" },
	{ import = "partials.plugins.gitsigns" },
	{ import = "partials.plugins.lint" },
	{ import = "partials.plugins.lazydev" },
	{ import = "partials.plugins.lsp" },
	{ import = "partials.plugins.lspkeys" },
	{ import = "partials.plugins.lualine" },
	{ import = "partials.plugins.mini" },
	{ import = "partials.plugins.neocord" },
	{ import = "partials.plugins.neotest" },
	{ import = "partials.plugins.noice" },
	{ import = "partials.plugins.obsidian" },
	{ import = "partials.plugins.persistence" },
	{ import = "partials.plugins.remote-nvim" },
	{ import = "partials.plugins.render-markdown" },
	{ import = "partials.plugins.smart-splits" },
	{ import = "partials.plugins.snacks-nvim" },
	{ import = "partials.plugins.tabby" },
	{ import = "partials.plugins.treesitter" },
	{ import = "partials.plugins.which-key" },
	{ import = "partials.plugins.yanky" },
})
