vim.keymap.set("n", "<leader>lgD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
vim.keymap.set("n", "<leader>lgd", vim.lsp.buf.definition, { desc = "Go to definition" })
vim.keymap.set("n", "<leader>lgt", vim.lsp.buf.type_definition, { desc = "Go to type" })
vim.keymap.set("n", "<leader>lgi", vim.lsp.buf.implementation, { desc = "List implementations" })
vim.keymap.set("n", "<leader>lgr", vim.lsp.buf.references, { desc = "List references" })
vim.keymap.set("n", "<leader>lgn", vim.diagnostic.goto_next, { desc = "Go to next diagnostic" })
vim.keymap.set("n", "<leader>lgp", vim.diagnostic.goto_prev, { desc = "Go to previous diagnostic" })
vim.keymap.set("n", "<leader>le", vim.diagnostic.open_float, { desc = "Open diagnostic float" })
vim.keymap.set("n", "<leader>lH", vim.lsp.buf.document_highlight, { desc = "Document highlight" })
vim.keymap.set("n", "<leader>lS", vim.lsp.buf.document_symbol, { desc = "List document symbols" })
vim.keymap.set("n", "<leader>lwa", vim.lsp.buf.add_workspace_folder, { desc = "Add workspace folder" })
vim.keymap.set("n", "<leader>lwr", vim.lsp.buf.remove_workspace_folder, { desc = "Remove workspace folder" })
vim.keymap.set("n", "<leader>lws", vim.lsp.buf.workspace_symbol, { desc = "List workspace symbols" })
vim.keymap.set("n", "<leader>lh", vim.lsp.buf.hover, { desc = "Trigger hover", noremap = false })
vim.keymap.set("n", "<leader>ls", vim.lsp.buf.signature_help, { desc = "Signature help" })
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Rename symbol" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Code action", noremap = false })
vim.keymap.set("n", "<leader>lf", vim.lsp.buf.format, { desc = "Format" })
